import net.fabricmc.loom.task.RemapJarTask
plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.gradleup.shadow' version '9.4.3'
}

version = project.mod_version
group = project.maven_group

repositories {
    maven { url 'https://maven.fabricmc.net' }
    maven { url 'https://maven.parchmentmc.org' }
    maven { url "https://maven.kyrptonaught.dev" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	//Discord Bridge
	shadow implementation("net.dv8tion:JDA:6.4.1") { exclude module: 'opus-java' }

	//Javalin
	shadow implementation("io.javalin:javalin:7.2.2")
}

loom {
	accessWidenerPath = file("src/main/resources/lembackend.classtweaker")
}

configurations {
    shadow
    compileOnly.extendsFrom(shadow)
}

shadowJar {
    configurations = [project.configurations.shadow]
    setProperty("zip64", true)
    setProperty("minimizeJar", true)
	destinationDirectory = file("${buildDir}/tmp/allJar")
	relocate 'okhttp3', 'net.dv8tion.shaded.okhttp3'
	relocate 'okio' , 'net.dv8tion.shaded.okio'

	//Exclude META-INF entries of shaded deps
	exclude('META-INF/**')
	// include() upsets shadow, so use from() instead
	from('LICENSE.md', 'NOTICE.txt')
	from('licenses') {
		into('licenses')
	}
}

base {
	archivesName = project.archives_base_name
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.build.dependsOn(tasks.shadowJar)
tasks.build.dependsOn(shadowJar)
jar {
    dependsOn(shadowJar)
    mustRunAfter(shadowJar)

    inputs.property "projectName", project.name

    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from(zipTree(shadowJar.archiveFile)) {
        exclude "META-INF/MANIFEST.MF"
    }
}